//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.18 at 02:34:50 PM IST 
//


package com.planetsconcrete.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for planet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="planet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="planetNode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PlanetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "planet", propOrder = {
    "planetNode",
    "planetName"
})
public class Planet {

    @XmlElement(required = true)
    protected String planetNode;
    @XmlElement(name = "PlanetName", required = true)
    protected String planetName;

    /**
     * Gets the value of the planetNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanetNode() {
        return planetNode;
    }

    /**
     * Sets the value of the planetNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanetNode(String value) {
        this.planetNode = value;
    }

    /**
     * Gets the value of the planetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanetName() {
        return planetName;
    }

    /**
     * Sets the value of the planetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanetName(String value) {
        this.planetName = value;
    }

}
